### ISSUE TITLE
How to use this mod?

### ISSUE THREAD

**Issue by LeRutY** [ineedbots/cod2m_bot_warfare#1]
Asking because I can´t get the server to launch. "z_server" outputs this: "CoD2M Bot Warfare server closed or dropped... server restarts."

**Comment by jrayner00** [comment]
Hey LeRutY, did you manage to figure it out? I would love to get this working somehow.

**Comment by CrazyCSIW6** [comment]
Clone this git repo: https://github.com/ineedbots/cod2m
Don't download it as ZIP, that won't work.
Run generate.bat
Go to build and compile the solution using Visual Studio
Put d3d9.dll in your Call of Duty 2 directory [I didn't have much luck with the Steam version, retail 1.3 worked however]

If you're hosting a listen server:
Get the mods directory from this git repo: https://github.com/ineedbots/cod2m_bot_warfare
Put the mods directory in your Call of Duty 2 directory
Start the game with +seta fs_game "mods/bots" in your launch parameters

**Comment by CrazyCSIW6** [comment]
If you don't know how to do any of that, this isn't for you.

**Comment by Beamxrz** [comment]
Sorry, but I can't get this mod to work... I did literally everything right, but I keep getting "script compile errors". When I open it up with "z_deploy", I get a "wm_quickmessage" error, or when I open it up with the shortcut, I get a "wm_setting" error.

![ScreenShot_20230602180942](https://github.com/ineedbots/cod2m_bot_warfare/assets/133183208/27b3b071-c254-4a1d-b73a-dc82c3c137d4)

**Comment by jrayner00** [comment]
> Sorry, but I can't get this mod to work... 

Did you get any joy getting this functional my man?

**Comment by ineedbots** [comment]
this is compatible with libcod
